[package]
name = "mastermind_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
laura = []
default = []

[dependencies]
#rayon = "1.5.3"

[profile.release]
debug = true
lto = true
